# Generated by Django 4.2.1 on 2023-06-20 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код купона')),
                ('valid_from', models.DateTimeField(verbose_name='Действителен от')),
                ('valid_to', models.DateTimeField(verbose_name='Действителен до')),
                ('discount', models.IntegerField(help_text=' Значение в процентах( от 0 to 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка в %')),
                ('active', models.BooleanField(verbose_name='Активность')),
            ],
        ),
    ]
