# Generated by Django 4.2.1 on 2023-06-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Платеж №'),
        ),
    ]
